### ISSUE TITLE
problem parsing some mission files

### ISSUE THREAD

**Issue by Super-truite** [lefufu/PylGBMiMec#2]
key error for grid index in ObjIndex[Object.type] line 96 in mission_class
for some missions.
Problematic missions attached.
[missions_leading_to_problems.zip](https://github.com/lefufu/PylGBMiMec/files/5752287/missions_leading_to_problems.zip)

**Comment by lefufu** [comment]
Hello. Problem is simple : maps min and max coordinates are defined in map_size.py. The coordinates are the border of the "usable" map. But a lot of triggers have been put outside limits of the maps !
So the "Grid" computed by findGrid in mission_class.py was false... I added a fix to set grid to zero or map max in this function, to cope woth object placed outside map (no roubst way to guess what should be the min and max limit, it depend of users). Anyway, Grid are thinked to speedup search for blocks (mostly massive object number), which may not be placed outside map...
New mission_class.py uploaded.

**Comment by lefufu** [comment]
see above
